version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: appsignal
    versions:
    - 2.11.5
    - 2.11.6
    - 2.11.8
    - 2.11.9
    - 3.0.0
    - 3.0.1
    - 3.0.2
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: autoprefixer-rails
    versions:
    - 10.2.0.0
